import type { Metadata } from "next";
import localFont from 'next/font/local'
import { Abril_Fatface } from 'next/font/google'
import "./globals.css";

import Header from "./ui/Header";
import Footer from "./ui/Footer";
import { Suspense } from "react";
const Gilroy = localFont({
  src: [
    {
      path: "./Fonts/Gilroy-Thin.woff2",
      weight: '100',
      style: 'normal',
    },
    {
      path: "./Fonts/Gilroy-Light.woff2",
      weight: '300',
      style: 'normal',
    },
    {
      path: "./Fonts/Gilroy-Regular.woff2",
      weight: '400',
      style: 'normal',
    },
    {
      path: "./Fonts/Gilroy-Medium.woff2",
      weight: '500',
      style: 'normal',
    }
  ]
})

export const metadata: Metadata = {
  title: "Обивка и ремонт мягкой мебели в Орехово-Зуево",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Gilroy.className + " bg-white"}>
        <Suspense>
          <Header />
          {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
