import type { Metadata } from "next";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: "Наша команда | Обивка и ремонт мягкой мебели в Орехово-Зуево",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-dvh">{children}</main>
  );
}
